# Generated by Django 5.1 on 2024-08-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options_alter_author_email_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=50)),
                ('stock_count', models.IntegerField()),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processsing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
