# Generated by Django 4.2.15 on 2024-08-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_cash_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='processsing_fee',
            new_name='processing_fee',
        ),
        migrations.AlterField(
            model_name='cash',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(),
        ),
    ]
